#
#  Author: Hari Sekhon
#  Date: 2022-01-27 18:55:16 +0000 (Thu, 27 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Nagios-Plugins
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/HariSekhon
#

---
name: Docker Build (Debian)

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
      - .github/
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
      - .github/
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false

jobs:
  docker_build:
    name: Docker Build
    uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo_tags: |
        harisekhon/nagios-plugins:debian
        ghcr.io/harisekhon/nagios-plugins:debian
      dockerfile-repo: HariSekhon/Dockerfiles
      context: Dockerfiles/nagios-plugins-debian
      debug: ${{ github.event.inputs.debug }}
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    if: github.ref_name == 'master' || github.ref_name == 'main' || github.ref_name == 'docker'
    permissions:
      contents: read
      packages: write
