#
#  Author: Hari Sekhon
#  Date: 2022-01-27 18:55:16 +0000 (Thu, 27 Jan 2022)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Nagios-Plugins
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#  https://www.linkedin.com/in/harisekhon
#

---
name: DockerHub Build (Alpine)

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

jobs:
  docker_build:
    name: Docker Build
    uses: HariSekhon/GitHub-Actions/.github/workflows/docker_build.yaml@master
    with:
      repo: harisekhon/nagios-plugins
      tags: alpine
      dockerfile-repo: HariSekhon/Dockerfiles
      context: Dockerfiles/nagios-plugins-alpine
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
    if: github.ref_name == 'master' || github.ref_name == 'main' || github.ref_name == 'docker'
    permissions:
      contents: read
      packages: write
